spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: Madarfakar94*
    url: jdbc:mariadb://localhost:3306/activities
    username: brinchi
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
